// <auto-generated />
using System;
using Company.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.Migrations
{
    [DbContext(typeof(DbClassContext))]
    partial class DbClassContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Company.Models.Buses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("numberSeat")
                        .HasColumnType("int");

                    b.Property<string>("stateNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Company.Models.Drivers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contactInformation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverLicense")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("patronymic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Company.Models.Flights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("numberFlight")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("timeArrival")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("timeDeparture")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Company.Models.Passengers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("passportData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("patronymic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Company.Models.PersonalRoles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("PersonalRoles");
                });

            modelBuilder.Entity("Company.Models.Routes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ArrivalStopsId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureStopsId")
                        .HasColumnType("int");

                    b.Property<string>("intermediateStops")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("light")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("ArrivalStopsId");

                    b.HasIndex("DepartureStopsId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Company.Models.Stops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nameStop")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("timeParking")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("Company.Models.Tickets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<int>("StopId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("numberSeat")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("StopId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Company.Models.Flights", b =>
                {
                    b.HasOne("Company.Models.Buses", "Bus")
                        .WithMany("flightsId")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Models.Drivers", "Driver")
                        .WithMany("flightsId")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Models.Routes", "Route")
                        .WithMany("flightsId")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Company.Models.Routes", b =>
                {
                    b.HasOne("Company.Models.Stops", "cityArrival")
                        .WithMany("routesArrival")
                        .HasForeignKey("ArrivalStopsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Company.Models.Stops", "cityDeparture")
                        .WithMany("routesDeparture")
                        .HasForeignKey("DepartureStopsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cityArrival");

                    b.Navigation("cityDeparture");
                });

            modelBuilder.Entity("Company.Models.Tickets", b =>
                {
                    b.HasOne("Company.Models.Flights", "Flight")
                        .WithMany("ticketId")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Models.Passengers", "Passenger")
                        .WithMany("ticketId")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Models.Stops", "Stop")
                        .WithMany("ticketId")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("Company.Models.Buses", b =>
                {
                    b.Navigation("flightsId");
                });

            modelBuilder.Entity("Company.Models.Drivers", b =>
                {
                    b.Navigation("flightsId");
                });

            modelBuilder.Entity("Company.Models.Flights", b =>
                {
                    b.Navigation("ticketId");
                });

            modelBuilder.Entity("Company.Models.Passengers", b =>
                {
                    b.Navigation("ticketId");
                });

            modelBuilder.Entity("Company.Models.Routes", b =>
                {
                    b.Navigation("flightsId");
                });

            modelBuilder.Entity("Company.Models.Stops", b =>
                {
                    b.Navigation("routesArrival");

                    b.Navigation("routesDeparture");

                    b.Navigation("ticketId");
                });
#pragma warning restore 612, 618
        }
    }
}
